---
- name: Distribuição de Software Base via Chocolatey
  hosts: all
  gather_facts: false
  
  # A elevação agora vai funcionar porque a flag gráfica do AWX está ativa!
  become: true
  become_method: runas
  become_user: SYSTEM

  tasks:
    - name: Garantir que o Chocolatey esta instalado no host
      ansible.windows.win_shell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      args:
        creates: C:\ProgramData\chocolatey\bin\choco.exe

    - name: Instalar utilitarios essenciais de operacoes
      chocolatey.chocolatey.win_chocolatey:
        name:
          - 7zip
          - notepadplusplus
          - sysinternals
        state: present
